const COUNT_PHOTOS = 25;
const COUNT_OF_COMMENTS_SHOWN = 5;
const MAX_COUNT_HASHTAG = 5;
const HASTAG_REGEX = /^#[a-zа-яё0-9]{1,19}$/i;

export { COUNT_PHOTOS, COUNT_OF_COMMENTS_SHOWN, MAX_COUNT_HASHTAG, HASTAG_REGEX };
